import Head from 'next/head'
import Layout from '@/components/Layout'
import AnimatedText from '@/components/AnimatedText';
import Image from 'next/image'
import ProfilePic from "../../public/images/profile/jonatan.jpg";
import Link from 'next/link';
import { LinkArrow } from '@/components/Icons';
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      
      </Head>
      <main className="flex items-center text-dark w-full min-h-screen">
      <Layout className='pt-0'>
        <div className="flex items-center justify-center w-full">
          <div className='w-1/4 flex items-left justify-left'>
            <Image src={ProfilePic} alt="Profile" width={400} height={400} className=" w-full h-auto" />
          </div>
          <div className="w-1/2 flex flex-col items-center self-center ml-20">
           
            <AnimatedText 
              text="Crafting intelligent embedded systems, from concept to code under real-world constraints"
              className="!text-6xl !text-left" />
            <p className="my-4 text-base font-medium md:text-lg text-left">
              I specialize in developing efficient and reliable software for embedded systems, ensuring optimal performance and adherence to real-time requirements.
              With a solid foundation in embedded systems engineering, I excel in designing and implementing software solutions that meet the unique challenges of resource-constrained environments.
            </p>
            <div className="flex items-center self-start mt-2">
              <Link href="/cv.pdf" target={"_blank"}
              className="flex items-center bg-dark text-light p-2 px-6 
              rounded-lg text-lg font-semibold hover:bg-light hover:text-dark
              border border-solid border-transparent hover:border-dark"
              download={true}>Resume <LinkArrow className={"w-6 ml-1"}/> </Link>

              <Link href="mailto:kamdadibreyjonatan@gmail.com" target={"_blank"}
              className="ml-4 text-lg font-medium capitalize text-dark underline"
              >Contact</Link>
            </div>
          </div>
          </div>
      </Layout>
      </main>
    </>
  )
}
